# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae3c6716b70d00888c55eb7b50766dfe46ba57c98b791533beb26560405adf9237065c8e24595170795ec153c871438d358edf8c163d2babe2e7597860f53f93

test:
  secret_key_base: 6238f2d77516596d7f8d64c5ed270db47c0754bb732f61744e0f33f119dca9c6754c739f0d45cdd0c4d64c5a5a016472648540baa9da799da708f514a56fa86f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
